### ISSUE TITLE
Enable OAuth

### ISSUE THREAD

**Issue by RichardLitt** [BeagleLab/beagle#133]
Currently blocked using Oauth.io on branch `feature/106-oauth-io`, reported here: https://github.com/oauth-io/oauth-js/issues/63

**Comment by RichardLitt** [comment]
Branch `feature/106-oauth` is an attempt to get an OAuth chrome extension example working. 
Branch `feature/106-oauth-two` is an attempt to get OAuth2 working through the Chrome Developers example.

**Comment by RichardLitt** [comment]
Branch `feature/106-oauth-io-issue-55` is an attempt at following https://github.com/oauth-io/oauthd/issues/52. Even though I have added a button, `oauth.js` directly into the viewer, and jQuery both in `main.min.js` and into the viewer's `head`, this doesn't work. Currently, a pop-up is opened and then closed immediately. Non of my blockers are on, so I'm entirely confused as to why it isn't working. It says that `r.get` fails, although the code comment says just include jQuery to make that work. I am not sure how including jQuery enables the method `get()`, though, which may have something to do with this failing. I do not understand why the pop up closes immediately, or how this would work from inside of `main.min.js` eventually anyway.

**Comment by RichardLitt** [comment]
This suggests using the chrome `identity` api. https://groups.google.com/a/chromium.org/forum/m/#!topic/chromium-extensions/wKNy65FqJSY It is unclear how to implement this directly.

**Comment by RichardLitt** [comment]
The OAuth.io people suggest: 
- https://github.com/oauth-io/oauthd/issues/52. I've tried it and opened an issue, based on `feature/106-oauth-io-issue-55`. (should be `issue-52`, actually). 
- http://stackoverflow.com/questions/27282540/cross-browser-request-from-chrome-extension-with-oauth-io. I'm not getting an error like this, so this isn't the most helpful. 
- http://stackoverflow.com/questions/23313900/oauth-io-oauth-js-with-chrome-extension Also not getting this error.

**Comment by RichardLitt** [comment]
Many of the branches this work is based off of are called `feature/106-*` due to the first attempt to get this working, in https://github.com/BeagleLab/beagle/issues/106.

**Comment by jbenet** [comment]
One more to try https://developer.chrome.com/extensions/tut_oauth ?

**Comment by RichardLitt** [comment]
Will do. Was just attempting #147 using hello.js; ran into a problem, which I've run into before here, where I can't access any of the variables inside another content script or background script from another. Just found out that is due to an [isolated world](http://stackoverflow.com/a/5162742/1166929) policy, which means I need to not use `onClick` but `addEventListener`. This may have caused a problem earlier on. Going to see if I can get this working first, then I'll go back through the developer.chome.com extension tutorial again, describing it here.

**Comment by RichardLitt** [comment]
Well, that didn't work. Learned some more things, documented them in #147.

**Comment by RichardLitt** [comment]
The continual sign in issue is due to any API you are using not being enabled in the Chrome Developers Console. See [here](https://github.com/dhatanian/demo-gmail-api/issues/1).

**Comment by RichardLitt** [comment]
This extension works and can be gleaned for useful information: https://github.com/dhatanian/demo-gmail-api

**Comment by RichardLitt** [comment]
Opened issue to deal with pop-up jQuery problem: https://github.com/oauth-io/oauthd/issues/152

**Comment by RichardLitt** [comment]
Landed using oauth.io.
