### ISSUE TITLE
Try using chrome.identity

### ISSUE THREAD

**Issue by RichardLitt** [BeagleLab/beagle#144]
Trying this, outlined here: http://stackoverflow.com/questions/25044936/chrome-identity-user-authentication-in-a-chrome-extension

Work is on `feature/106-stackoverflow` - currently blocked.

**Comment by RichardLitt** [comment]
Taking code out of the comment because it gets lost on in there - I wish there was a better way of displaying commit messages. 

> On the background page, this loads on the extension launch - on Chrome launch, basically, which is suboptimal. We want it to verify on User interaction, which means it needs to be done in main.js. However, the code provided basically destroys this possibility, as it doesn't send back anything, and continually asks for your password. I don't know how to fix this at the moment - I'm still very unfamiliar with the Chrome identity API. #144

Related to #133.

**Comment by RichardLitt** [comment]
So, I've been trying today to make this work by following the steps in [Google's tutorial](https://developer.chrome.com/extensions/app_identity) for `chrome.identity`. The main issue is that I don't want to publish this to the app store, so I need to figure out how to get the key to put in my manifest. I've asked a question about how to do this, [here](http://stackoverflow.com/questions/30025156/chrome-identity-in-an-unpublished-extension). This [question](http://stackoverflow.com/questions/23741459/chrome-identity-in-development) is very similar, but in this case the person already had a developed app.

It looks like this tutorial may also be only for an Application, not an extension; it suggests you set up a Chrome application to get a client id in the [Developer's console](https://console.developers.google.com), which just doesn't sound right at all. (That the dev console doesn't really provide urls for permissions for chrome extensions is also worrying; I have to get the google contacts API urls from [their own page](https://developers.google.com/google-apps/contacts/v3/?hl=en_US). I am increasingly worried this entire ecosystem may just be an afterthought for Chrome).

**Comment by RichardLitt** [comment]
So, I've basically got this working, but it's pretty buggy. I was able to get a key back by calling from `main.min.js`, but I haven't been able to replicate signing in on my friend's laptop, or in incognito mode, and I'm still pretty confused about the key stuff. 

More importantly, I really agree with this one guy who had similar issues. Actually, Chrome's UI appears to have changed, because his issues are slightly different - he get's redirected to settings, whereas I don't. But anyway, he did the same steps, and then said this:

> I've had a change of heart about getAuthToken being better since I wrote the last message and went back to the normal auth flow. Three reasons:

> 1. The overlay that pops up is pretty bad UI/UX. It appears pretty much wherever it feels like on the screen (having nothing to do with the browser) and appears like a malicious popup you'd expect on a torrent or porn site. I've come to feel that it's too jarring and confusing for the user to be acceptable.

> 2. This may only be a developer problem, but if I want to switch accounts inside my extension, going with getAuthToken makes that more difficult because the accounts are tied into Chrome itself. For instance, if I am a developer testing interaction between two users, if I want to switch from user A to user B, I have to not only switch in the app, but switch Chrome users as well. And these dummy users will need to have chrome sync and all that. The weird overlay doesn't, from what I can tell, allow easy user switching. The current user seems hardcoded at the top right.

> 3. I've got other 3rd party logins in the extension, too. Having this the getAuthToken flow be so different is weird from a UI/UX perspective. Whereas reason #1 above was "the UX is bad in a absolute sense", what I'm saying here is "it's even worse when the UX of your other auth flows is different". This is true, not only for the user, but for the developer, too.

> The auto-refreshing of tokens is nice and all that and I understand there are advantages, but, IMO and in my special case, the getAuthToken system isn't acceptable in practice.

I couldn't agree more. I don't like the pop up I saw, it was in a weird part of the screen, and we're going to want to switch accounts and have other OAuth entry points. So, I am going to give up on `chrome.identity`, permanently.

**Comment by RichardLitt** [comment]
Further, the key has to change for each user using Beagle, as it says in the link on the top. Yeah, let's just avoid `chrome.identity` and find a way to use OAuth2 normally.

**Comment by adammarblestone** [comment]
"The main issue is that I don't want to publish this to the App Store"

Why not?

**Comment by RichardLitt** [comment]
It's still in development mode. There will be a time for that, but I feel like putting a half-done product up just to get the key is strange?

**Comment by RichardLitt** [comment]
Note to self: take a break before writing posts cutting out one path, not after. This is all up for discussion, I just feel that `chrome.identity` isn't the way to go right now.

**Comment by adammarblestone** [comment]
I don't see anything wrong with putting it on the App Store "just" to get a key...

**Comment by RichardLitt** [comment]
Well, it also is am implementation decision. It means we're going with Chrome's native way of dealing with this, and ties us to Chrome and this UI until we have time to go back and refactor. It means we can't login in with any other providers without reimplimenting; so, Twitter, Facebook, GitHub, etc. I think that may be something we want in the future, as using OAuth to access their APIs is afaik necessary. 

I'm also unsure about multiple accounts - I think we'll need them, and `chrome.identity` won't let us have them. Basically, it's a lot of negatives, and the only positive being that we have a potentially buggy and badly designed UI we can push out faster.

**Comment by adammarblestone** [comment]
Got it!

**Comment by RichardLitt** [comment]
Going to just use Oauth.io for now.
