### ISSUE TITLE
Create a Conversations list component

### ISSUE THREAD

**Issue by RichardLitt** [BeagleLab/beagle#176]
![screen shot 2015-05-15 at 5 16 30 pm](https://cloud.githubusercontent.com/assets/910753/7651022/534010a4-fb26-11e4-800e-f482b99f3565.png)

**Comment by RichardLitt** [comment]
This should be ordered by last interaction: conversations which are edited or shared more recently are higher on the list.

**Comment by NDuma** [comment]
If there is room for a menu:
 - Last interaction
 - Created
 - Topic Alpha A<-Z + A->Z
 - {#}Tags

**Comment by NDuma** [comment]
![inspiration_beagle_menu_conversation](https://cloud.githubusercontent.com/assets/8163869/7792040/ef1d835e-025f-11e5-8b7d-ae093db5b03c.png)

**Comment by RichardLitt** [comment]
That sounds smart to me. Makes it a bit more complicated, might be good to have this as another issue and put it further down the pipeline.

**Comment by RichardLitt** [comment]
Opened issue #204 for the menu. Otherwise, done.
