### ISSUE TITLE
Flesh out a user model

### ISSUE THREAD

**Issue by RichardLitt** [BeagleLab/beagle#182]
Save persistent users to the database.

**Comment by RichardLitt** [comment]
Hey @jbenet: so, here is the gist of the problem. We are currently PouchDB on the client side, and CouchDB in the server for a remote db. These databases are synced. 

For user accounts, I've gone with [pouchdb-authentication](https://github.com/nolanlawson/pouchdb-authentication), which doesn't have OAuth integration, as I found out today [here](https://github.com/nolanlawson/pouchdb-authentication/issues/5). The problem is this: there are multiple functions, `signIn` and `signUp` which require a user object with an email, a password, and a username in order to work. We could provide something semi-random as the password, but it will never be as good or secure at all if it is not provided by the user in an iframe or separated logically from the client side code. You can see how this code works [here](https://github.com/nolanlawson/pouchdb-authentication/blob/master/lib/index.js) - it's a short read. The README is also good. 

OAuth currently works by clicking on a React button in the UI, which calls an OAuth modal, which returns google (or GitHub) profile information. This includes a name, email, and most importantly, your google id, an access token, and a id token. The Oauth tokens should be  stored in a link object, as [here in the schema](https://github.com/BeagleLab/beagle/blob/master/js/data/schema.js#L49-L55). OAuth is used to get contacts and to make storage easier. 

The issue is that `pouchdb-authentation` requires passwords, and OAuth negates the need for them. If you look at the pouchdb-auth code, you can see that it stores to a url, which I believe comes directly from the db itself. What we could do is use a proxy server here to provide unique hashes that the user wouldn't be able to see.

Thoughts?

**Comment by jbenet** [comment]
something like 
```js
// So the deal is that the client will run OAuth against some server
// and will acquire a token. This token will be sent to our auth-server.
// Our auth-server will then have to do two things:
// - verify the token is good (make a request to the OAuth provider)
// - run the desired auth operation on couchdb
// So it should look something like this:


// client -- the client webapp or extension
// auth-server -- the authentication server
// couchdb -- well, couchdb.


// get this from the client's request
var oauthInfo = {
  provider: "twitter.com",
  account: "@juanbenet",
  token: "some-oauth-token",
}

// authServerKey SHOULD NOT be leaked. probably set it through an ENV VAR
var authServerKey = "some random string. will be used to gen passwords."

function signup(beagleUsername, oauthInfo, clientcb) {
  
  verifyOAuthToken(oauthInfo, function(err) {
    if (err != null) {
      // ok something went wrong
      clientcb("error ... ")
      return
    }

    // ok looks good. we can signup user.

    // the password is basically not used to authenticate at all.
    // we use it merely because couchdb forces us to. At this point
    // we've verified auth (with oauth) and have a valid token, so
    // we are good. We thus set the password to a user-specific 
    // random string deterministically generated (so we can login
    // later, too). let's say this is: 
    var salt = newID() // generate some random string
    var pass = sha256( username + authServerKey + salt )

    var user = {
      username: beagleUsername,
      password: pass,
      salt: salt, // store salt in user somewhere
      oauthInfo: { // store the oauth data somwhere.
        provider: oauthInfo.provider,
        account: oauthInfo.account,
      },
      ... // whatever else we need
    }

    couchdb.signup(user, function(err, ...) {
      if (err != null) {
        // failed to sign up
        clientcb("error ... ")
        return
      }

      // ok we're signed up. return the session id to the client
      clientcb(null, ...)
    })
  })
}


function login(beagleUsername, oauthtoken, clientcb) {

  
  // first, check beagleUsername matches oauthtoken
  verifyOAuthUser(beagleUsername, oauthinfo, function(err) {
    if (err != null) {
      // ok something went wrong
      clientcb("error ... ")
      return
    }

    // ok, beaglename checks out as matching oauthinfo.

    verifyOAuthToken(oauthInfo, function(err) {
      if (err != null) {
        // ok something went wrong
        clientcb("error ... ")
        return
      }

      // ok looks good. we can login user.
      var user = get user from couchdb

      var pass = sha256( username + authServerKey + user.salt )

      // or whatever
      couchdb.login(username, pass, function(err, ...) {
        if (err != null) {
          // failed to log in
          clientcb("error ... ")
          return
        }
        // ok we're logged up
        clientcb(null, sessionid ...)
      })
    })
  })
  
}


// check that beagleUser matches oauthInfo.
func verifyOAuthUser(beagleUser, oauthInfo, cb) {

  var user = couchdb.users.get({username: beagleuser})

  // check the provider + accounts match
  var ok = (user.oauthInfo.provider == oauthInfo.provider) &&
       (user.oauthInfo.account == oauthInfo.account)

  if (!ok) {
    cb("error ...")
  } else {
    cb(null, ...)
  }
}


// check that oauthInfo.token is valid
func verifyOAuthToken(beagleUser, oauthInfo, cb) {

  // make a request to the provider that verifies oauth token
  // there should be an example of this somewhere.
  oauthlib.verify(oauthInfo.provider, oauthInfo.account, oauthInfo.token, function(err, ...) {
    if (err != null) {
      cb("error: token invalid")
      return
    }

    cb(null) // checks out.
  })
}
```

it's definitely got the weakness that the serverKey is like a master password. but if that server were to do anything with an admin user, it's the exact same security anyway. (admin users can do anything, and often webapps use admin users for some things)

**Comment by jbenet** [comment]
also, i just found this: https://auth0.com/why-auth0 seems to have oauth baked in and handle everything

**Comment by RichardLitt** [comment]
I would consider this done, for now.
